# Generated by Django 3.1.5 on 2021-01-14 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start_date',), 'verbose_name': 'Veranstaltung', 'verbose_name_plural': 'Veranstaltungen'},
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'ordering': ('name',), 'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
        migrations.AlterModelOptions(
            name='eventformat',
            options={'ordering': ('name',), 'verbose_name': 'Format', 'verbose_name_plural': 'Formate'},
        ),
        migrations.AlterModelOptions(
            name='eventspeaker',
            options={'ordering': ('last_name',), 'verbose_name': 'Referent*in', 'verbose_name_plural': 'Referent*innen'},
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventformat',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventcategory', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='eventspeaker',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Biografie'),
        ),
        migrations.AlterField(
            model_name='eventspeaker',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='eventspeaker',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='eventspeaker',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='eventspeaker',
            name='phone',
            field=models.CharField(blank=True, max_length=64, verbose_name='Tel'),
        ),
        migrations.AlterField(
            model_name='eventspeaker',
            name='social_url',
            field=models.URLField(blank=True, verbose_name='Soziale Medien'),
        ),
        migrations.AlterField(
            model_name='eventspeaker',
            name='url',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
