# Generated by Django 3.1.5 on 2021-01-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(max_length=255, verbose_name='Ort'),
        ),
    ]
