# Generated by Django 4.2.20 on 2025-10-05 11:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_show_in_all_events_alter_eventhighlight_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSliderImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="angelegt am"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, verbose_name="geändert am"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Titel"),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Untertitel"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="hero_slider/", verbose_name="Bild"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Niedrigere Zahlen werden zuerst angezeigt",
                        verbose_name="Reihenfolge",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Gibt an, ob das Bild im Slider angezeigt werden soll",
                        verbose_name="Aktiv",
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        help_text="Optionale URL, zu der der Slider verlinkt",
                        verbose_name="Link URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero Slider Bild",
                "verbose_name_plural": "Hero Slider Bilder",
                "ordering": ["order"],
            },
        ),
        migrations.AlterField(
            model_name="eventhighlight",
            name="event",
            field=models.ForeignKey(
                limit_choices_to={
                    "first_day__gte": datetime.date(2025, 10, 5),
                    "pub_status": "PUB",
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlight",
                to="events.event",
            ),
        ),
    ]
