# Generated by Django 3.1.5 on 2021-01-15 06:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210114_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventagenda',
            options={'ordering': ('start_time',), 'verbose_name': 'Programm', 'verbose_name_plural': 'Programme'},
        ),
        migrations.RemoveField(
            model_name='eventagenda',
            name='speaker_name',
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='test', verbose_name='Programm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventagenda',
            name='venue_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='wo'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='eventformat',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
    ]
