# Generated by Django 4.2.20 on 2025-10-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_herosliderimage_alter_eventhighlight_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="herosliderimage",
            name="show_title",
            field=models.BooleanField(default=False, verbose_name="Titel zeigen"),
        ),
        migrations.AlterField(
            model_name="herosliderimage",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Titel"),
        ),
    ]
