# Generated by Django 4.2.20 on 2025-10-09 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_herosliderimage_show_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="hero_slider_length",
            field=models.IntegerField(
                default=10000,
                help_text="Anzeigedauer pro Bild im Slider in Millisekunden",
                verbose_name="Slider Dauer pro Bild",
            ),
        ),
        migrations.AlterField(
            model_name="eventhighlight",
            name="event",
            field=models.ForeignKey(
                limit_choices_to={
                    "first_day__gte": datetime.date(2025, 10, 9),
                    "pub_status": "PUB",
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlight",
                to="events.event",
            ),
        ),
    ]
