# Generated by Django 3.1.5 on 2021-01-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210116_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_template',
            field=models.TextField(blank=True, verbose_name='Vorlage für Html Email'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='text_template',
            field=models.TextField(verbose_name='Vorlage für Text Email'),
        ),
    ]
