# Generated by Django 4.2.20 on 2025-10-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_eventhighlight_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="contact",
            field=models.TextField(blank=True, verbose_name="Kontakt"),
        ),
        migrations.AddField(
            model_name="home",
            name="impressum",
            field=models.TextField(blank=True, verbose_name="Impressum"),
        ),
        migrations.AddField(
            model_name="home",
            name="legals",
            field=models.TextField(blank=True, verbose_name="Rechtliche Hinweise"),
        ),
    ]
