# Generated by Django 4.2.20 on 2025-10-11 05:55

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_home_contact_home_impressum_home_legals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventhighlight",
            name="event",
            field=models.ForeignKey(
                limit_choices_to={
                    "first_day__gte": datetime.date(2025, 10, 11),
                    "pub_status": "PUB",
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlight",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="home",
            name="contact",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Kontakt"),
        ),
        migrations.AlterField(
            model_name="home",
            name="impressum",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Impressum"),
        ),
        migrations.AlterField(
            model_name="home",
            name="legals",
            field=ckeditor.fields.RichTextField(
                blank=True, verbose_name="Rechtliche Hinweise"
            ),
        ),
    ]
