# Generated by Django 3.1.5 on 2021-01-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20210116_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='label',
            field=models.CharField(default='E', max_length=64),
            preserve_default=False,
        ),
    ]
