# Generated by Django 4.2.20 on 2025-10-11 06:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_alter_eventhighlight_event_alter_home_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="privacy",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Datenschutz"),
        ),
    ]
