# Generated by Django 4.2.20 on 2025-10-12 20:16

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_home_privacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="nl_text",
            field=ckeditor.fields.RichTextField(
                blank=True, verbose_name="Text NL Signup"
            ),
        ),
        migrations.AddField(
            model_name="home",
            name="nl_title",
            field=models.CharField(
                default="Bleiben Sie auf dem Laufenden",
                max_length=255,
                verbose_name="Titel NL Signup",
            ),
        ),
        migrations.AlterField(
            model_name="eventhighlight",
            name="event",
            field=models.ForeignKey(
                limit_choices_to={
                    "first_day__gte": datetime.date(2025, 10, 12),
                    "pub_status": "PUB",
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlight",
                to="events.event",
            ),
        ),
    ]
