# Generated by Django 3.1.5 on 2021-01-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventformat',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Format'),
        ),
    ]
