# Generated by Django 3.1.5 on 2021-01-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20210116_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='label',
            field=models.CharField(default='A', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='attend_status',
            field=models.CharField(choices=[('registered', 'angemeldet'), ('waiting', 'Warteliste'), ('attending', 'nimmt teil'), ('absent', 'nicht erschienen'), ('cancelled', 'abgesagt')], max_length=10),
        ),
    ]
