# Generated by Django 4.2.20 on 2025-11-29 17:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_home_nl_text_home_nl_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vfll_recipient_payment",
                    models.CharField(
                        default="Verband der Freien Lektorinnen und Lektoren e. V.",
                        max_length=255,
                    ),
                ),
                (
                    "vfll_bank_account",
                    models.CharField(
                        blank=True,
                        default="GLS Bank // IBAN: DE67430609676032523702 // BIC: GENODEM1GLS",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="eventhighlight",
            name="event",
            field=models.ForeignKey(
                limit_choices_to={
                    "first_day__gte": datetime.date(2025, 11, 29),
                    "pub_status": "PUB",
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlight",
                to="events.event",
            ),
        ),
    ]
