# Generated by Django 3.1.5 on 2021-01-16 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20210116_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='maximum_attende',
            new_name='capacity',
        ),
    ]
