# Generated by Django 4.2.20 on 2025-11-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_sitesettings_alter_eventhighlight_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailBlacklist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="blacklist_message",
            field=models.TextField(
                default="Bitte kontaktieren Sie uns direkt, um sich anzumelden."
            ),
        ),
    ]
