# Generated by Django 4.2.20 on 2025-12-11 16:43

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_emailblacklist_sitesettings_blacklist_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="about_us",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Über uns"),
        ),
        migrations.AlterField(
            model_name="eventhighlight",
            name="event",
            field=models.ForeignKey(
                limit_choices_to={
                    "first_day__gte": datetime.date(2025, 12, 11),
                    "pub_status": "PUB",
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlight",
                to="events.event",
            ),
        ),
    ]
