# Generated by Django 4.2.20 on 2025-12-11 17:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_home_about_us_alter_eventhighlight_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="target_group",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Zielgruppe"
            ),
        ),
    ]
