# Generated by Django 3.1.5 on 2021-01-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20210117_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='mail_to_admin',
            field=models.BooleanField(default=False, verbose_name='m > admin'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='label',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
