# Generated by Django 3.1.5 on 2021-01-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20210117_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='label',
            field=models.CharField(max_length=64),
        ),
    ]
