# Generated by Django 4.2.20 on 2026-04-05 21:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid

def generate_tokens(apps, schema_editor):
    EventMember = apps.get_model("events", "EventMember")

    for obj in EventMember.objects.all():
        if not obj.survey_token:
            obj.survey_token = uuid.uuid4()
            obj.save(update_fields=["survey_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_target_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='survey_token',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.RunPython(generate_tokens),
        migrations.AlterField(
            model_name="eventmember",
            name="survey_token",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2026, 4, 5), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
