# Generated by Django 4.2.20 on 2026-04-05 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_eventmember_survey_token_alter_eventhighlight_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='survey_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
