# Generated by Django 3.1.5 on 2021-01-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20210117_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='moodle_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventspeaker',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='eventspeaker',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Vorname'),
        ),
    ]
