# Generated by Django 3.2.15 on 2026-04-21 09:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_eventhighlight_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='has_submitted_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2026, 4, 21), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
