# Generated by Django 3.1.5 on 2021-01-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20210121_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='students_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
