# Generated by Django 3.2.15 on 2026-04-22 20:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20260421_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='confirmation_place',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ort (Teilnahmebescheinigung)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='confirmation_signatory',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Unterzeichner*in (Teilnahmebescheinigung)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='confirmation_signatory_role',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Rolle Unterzeichner*in (Teilnahmebescheinigung)'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2026, 4, 22), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('docx_file', private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='confirmations/')),
                ('mail_sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Mailversand')),
                ('event_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='events.eventmember')),
            ],
            options={
                'verbose_name': 'Teilnahmebescheinigung',
                'verbose_name_plural': 'Teilnahmebescheinigungen',
            },
        ),
    ]
