# Generated by Django 4.2.20 on 2026-04-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_eventhighlight_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='confirmation_signatory',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='confirmation_signatory_role',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='confirmation_signatory_speaker',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Unterzeichner*in (Teilnahmebescheinigung) Dozent*in'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='confirmation_signatory_vfll',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Unterzeichner*in (Teilnahmebescheinigung) VFLL'),
        ),
    ]
