# Generated by Django 4.2.20 on 2026-05-01 06:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_confirmation_pdf_file_alter_eventhighlight_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='next_events_headline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nächste Veranstaltungen'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2026, 5, 1), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
