# Generated by Django 3.1.5 on 2021-01-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20210129_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventagenda',
            name='address_line',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zusatz'),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stadt'),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='postcode',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='PLZ'),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bundesland'),
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='street',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Straße'),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='address_line',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zusatz'),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stadt'),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='phone',
            field=models.CharField(blank=True, max_length=64, verbose_name='Tel'),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='postcode',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='PLZ'),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bundesland'),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='street',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Straße'),
        ),
    ]
