# Generated by Django 4.2.20 on 2026-05-01 06:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_home_next_events_headline_alter_eventhighlight_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='info_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Info-Text'),
        ),
    ]
