# Generated by Django 3.1.5 on 2021-01-31 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20210131_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventagenda',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='eventagenda',
            name='city',
        ),
        migrations.RemoveField(
            model_name='eventagenda',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='eventagenda',
            name='state',
        ),
        migrations.RemoveField(
            model_name='eventagenda',
            name='street',
        ),
    ]
