# Generated by Django 4.2.20 on 2026-05-02 16:42

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_home_info_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='testimonials',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Bewertungen'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2026, 5, 2), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
