# Generated by Django 3.1.5 on 2021-02-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20210202_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='memberships',
            field=models.CharField(blank=True, max_length=64, verbose_name='Mitgliedschaften'),
        ),
    ]
