# Generated by Django 4.2.20 on 2026-05-02 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_event_testimonials_alter_eventhighlight_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='speakers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventspeaker'),
        ),
    ]
