# Generated by Django 4.0.5 on 2026-05-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_home_speakers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='speakers',
        ),
    ]
