# Generated by Django 3.1.5 on 2021-02-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20210204_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='attention',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='attention_other',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='education_bonus',
            field=models.BooleanField(default=False, verbose_name='Bildungsprämie'),
        ),
    ]
