# Generated by Django 4.2.20 on 2026-05-04 15:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_remove_home_speakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspeaker',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Anzeigen'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2026, 5, 4), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
