# Generated by Django 4.2.20 on 2026-06-22 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_eventspeaker_show_alter_eventhighlight_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='send_registration_mail_to_admin',
            field=models.BooleanField(default=True, verbose_name='E-Mail an Admin senden'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_form',
            field=models.CharField(choices=[('s', 'Standard'), ('w', 'Willkommensveranstaltung'), ('m', 'MV/ZW'), ('f', 'Fachtagung 2022/MV'), ('f24', 'Fachtagung 2024/MV'), ('f26', 'Fachtagung 2026/MV')], default='s', max_length=3, verbose_name='Anmeldeformular'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2026, 6, 22), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
