# Generated by Django 3.1.5 on 2021-02-20 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20210208_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmember',
            options={'verbose_name': 'TeilnehmerIn', 'verbose_name_plural': 'TeilnehmerInnen'},
        ),
        migrations.AddField(
            model_name='eventmember',
            name='enroled',
            field=models.BooleanField(default=False, verbose_name='>m'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='attention',
            field=models.CharField(blank=True, max_length=64, verbose_name='aufmerksamen geworden durch'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='attention_other',
            field=models.CharField(blank=True, max_length=64, verbose_name='sonstige'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='events.event', verbose_name='Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Kurzbezeichnung'),
        ),
    ]
