# Generated by Django 3.1.5 on 2021-02-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20210220_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='moodle_id',
            field=models.PositiveIntegerField(default=0, verbose_name='MoodleID'),
        ),
    ]
