# Generated by Django 4.0.5 on 2026-06-27 11:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_event_send_registration_mail_to_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='confirmation_template',
            field=models.FileField(blank=True, help_text='PDF-Vorlage für die Teilnahmebescheinigung dieser Veranstaltung.', null=True, upload_to='confirmation_templates/', verbose_name='Vorlage Teilnahmebescheinigung (PDF)'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2026, 6, 27), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
