# Generated by Django 4.2.20 on 2026-06-28 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_confirmation_template_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventformat',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2026, 6, 28), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='attend_status',
            field=models.CharField(choices=[('registered', 'angemeldet'), ('waiting', 'Warteliste'), ('attending', 'nimmt teil'), ('absent', 'nicht erschienen'), ('cancelled', 'abgesagt'), ('done', 'teilgenommen')], max_length=10, verbose_name='Status'),
        ),
    ]
