# Generated by Django 3.1.5 on 2021-03-13 17:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_eventmember_moodle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(help_text='Datum: Picker verwenden oder in der Form tt.mm.jj; Zeit: hh:mm', verbose_name='Ende'),
        ),
        migrations.AlterField(
            model_name='event',
            name='open_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Anmeldefrist Beginn'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(help_text='Datum: Picker verwenden oder in der Form tt.mm.jj; Zeit: hh:mm', verbose_name='Beginn'),
        ),
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='angelegt am')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('start_date', models.DateField(help_text='Datum: Picker verwenden oder in der Form tt.mm.jj', verbose_name='Datum')),
                ('start_time', models.TimeField(help_text='hh:mm', verbose_name='Beginn')),
                ('end_time', models.TimeField(help_text='hh:mm', verbose_name='Ende')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_days', to='events.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
