# Generated by Django 3.1.5 on 2021-03-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20210313_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='open_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Anmeldefrist Beginn'),
        ),
    ]
