# Generated by Django 4.2.20 on 2026-07-05 06:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_eventformat_title_alter_eventhighlight_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='original_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventformat',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2026, 7, 5), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
