# Generated by Django 4.0.5 on 2026-08-30 13:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_eventmember_original_data_alter_eventformat_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPreRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='angelegt am')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('salutation', models.CharField(blank=True, choices=[('m', 'Herr'), ('f', 'Frau'), ('d', 'Divers')], max_length=1, verbose_name='Anrede')),
                ('academic', models.CharField(blank=True, max_length=40, null=True, verbose_name='Titel')),
                ('firstname', models.CharField(max_length=255, verbose_name='Vorname')),
                ('lastname', models.CharField(max_length=255, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=255, verbose_name='E-Mail')),
                ('agree', models.BooleanField(default=False, verbose_name='Einverständnis')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_registrations', to='events.event', verbose_name='Veranstaltung')),
            ],
            options={
                'verbose_name': 'Vormerkung',
                'verbose_name_plural': 'Vormerkungen',
                'ordering': ['-date_created'],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
