# Generated by Django 3.1.5 on 2021-03-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_auto_20210315_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='moodle_course_created',
            field=models.BooleanField(default=False),
        ),
    ]
