# Generated by Django 4.2.20 on 2026-10-03 13:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_eventpreregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='moodle_course_created',
        ),
        migrations.RemoveField(
            model_name='event',
            name='moodle_course_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='moodle_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='moodle_new_user_flag',
        ),
        migrations.RemoveField(
            model_name='event',
            name='moodle_standard_password',
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='moodle_id',
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2026, 10, 3), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
