# Generated by Django 3.1.5 on 2021-03-19 08:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_event_moodle_course_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='angelegt am')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('roleid', models.PositiveSmallIntegerField(choices=[(1, 'Manager*in'), (3, 'Trainer*in'), (5, 'Teilnehmer*in')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='eventday',
            options={'ordering': ('start_date',), 'verbose_name': 'Veranstaltungstag', 'verbose_name_plural': 'Veranstaltungstage'},
        ),
        migrations.AlterModelOptions(
            name='eventmember',
            options={'verbose_name': 'Teilnehmer*in', 'verbose_name_plural': 'Teilnehmer*innen'},
        ),
        migrations.CreateModel(
            name='EventMemberRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='angelegt am')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('eventmember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventmember')),
                ('memberrole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.memberrole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eventmember',
            name='role_id',
            field=models.ManyToManyField(through='events.EventMemberRoles', to='events.MemberRole'),
        ),
    ]
