# Generated by Django 3.1.5 on 2021-03-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_auto_20210319_0835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventMemberRoles',
            new_name='EventMemberRole',
        ),
    ]
