# Generated by Django 3.1.5 on 2021-03-19 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_auto_20210319_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmemberrole',
            options={'verbose_name': 'Rolle', 'verbose_name_plural': 'Rollen'},
        ),
        migrations.AlterField(
            model_name='event',
            name='speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='speaker_events', to='events.eventspeaker', verbose_name='Referent/-in'),
        ),
    ]
