# Generated by Django 3.1.5 on 2021-03-20 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_auto_20210319_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventspeakerthrough',
            options={'verbose_name': 'Referent*in', 'verbose_name_plural': 'Referent*innen'},
        ),
        migrations.AlterField(
            model_name='eventspeakerthrough',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='eventspeakerthrough',
            name='eventspeaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventspeaker', verbose_name='Referent*in'),
        ),
    ]
