# Generated by Django 3.1.5 on 2021-03-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_auto_20210320_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(help_text='Datum: Picker verwenden oder in der Form tt.mm.jj; Zeit: hh:mm', null=True, verbose_name='Ende'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(help_text='Datum: Picker verwenden oder in der Form tt.mm.jj; Zeit: hh:mm', null=True, verbose_name='Beginn'),
        ),
    ]
