# Generated by Django 3.1.5 on 2021-03-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_auto_20210321_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='close_date',
            field=models.DateField(blank=True, null=True, verbose_name='Anmeldefrist Ende'),
        ),
        migrations.AlterField(
            model_name='event',
            name='open_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Anmeldefrist Beginn'),
        ),
    ]
