# Generated by Django 3.1.5 on 2021-03-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_auto_20210322_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventagenda',
            options={'ordering': ('order',), 'verbose_name': 'Programm', 'verbose_name_plural': 'Programme'},
        ),
        migrations.AddField(
            model_name='eventagenda',
            name='order',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='Reihenfolge'),
            preserve_default=False,
        ),
    ]
