# Generated by Django 3.1.5 on 2021-03-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_auto_20210327_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventagenda',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Reihenfolge'),
        ),
    ]
