# Generated by Django 3.1.5 on 2021-03-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_auto_20210327_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='singular',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventagenda',
            name='order',
            field=models.PositiveIntegerField(help_text='Reihenfolge der Programme in der Anezige', verbose_name='Reihenfolge'),
        ),
    ]
