# Generated by Django 3.1.5 on 2021-04-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_auto_20210406_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='label',
            field=models.CharField(help_text='eindeutiger Kurzname', max_length=64, unique=True, verbose_name='Kurzname'),
        ),
    ]
