# Generated by Django 3.1.5 on 2021-04-06 16:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_auto_20210406_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='angelegt am')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=128, verbose_name='Nachname')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Tel')),
                ('url', models.URLField(blank=True, verbose_name='Website')),
                ('image', models.ImageField(blank=True, upload_to='speaker/')),
            ],
            options={
                'verbose_name': 'Pat*in',
                'verbose_name_plural': 'Pat*innen',
                'ordering': ('last_name',),
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Kapazität'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='location_events', to='events.eventlocation', verbose_name='Veranstaltungsort'),
        ),
        migrations.CreateModel(
            name='EventSponsorThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='angelegt am')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Veranstaltung')),
                ('eventsponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventsponsor', verbose_name='Pat*in')),
            ],
            options={
                'verbose_name': 'Pat*in',
                'verbose_name_plural': 'Pat*innen',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(through='events.EventSponsorThrough', to='events.EventSponsor', verbose_name='Pate,Patin'),
        ),
    ]
