# Generated by Django 3.1.5 on 2021-04-07 00:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_auto_20210406_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventagenda',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Programm'),
        ),
    ]
