# Generated by Django 3.1.5 on 2021-04-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_auto_20210407_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=15, verbose_name='Kapazität'),
        ),
    ]
