# Generated by Django 3.1.5 on 2021-04-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_auto_20210407_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='moodle_course_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'in Planung'), (4, 'Fortbildungen')], default=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='scheduled_status',
            field=models.CharField(choices=[('yet to scheduled', 'noch offen'), ('scheduled', 'terminiert')], default='scheduled', max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'findet statt'), ('deleted', 'verschoben'), ('cancel', 'abgesagt')], default='active', max_length=10),
        ),
    ]
