# Generated by Django 3.1.5 on 2021-04-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_auto_20210409_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'ordering': ('position',), 'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='moodle_course_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'in Planung'), (4, 'Fortbildungen')], default=4, verbose_name='Moodle Kurstyp'),
        ),
    ]
