# Generated by Django 3.1.5 on 2021-04-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_auto_20210412_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kurzbezeichnung'),
        ),
    ]
