# Generated by Django 3.1.5 on 2021-04-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_auto_20210414_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='first_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
