# Generated by Django 3.1.5 on 2021-04-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0057_auto_20210427_0459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='moodle_standard_passwort',
            new_name='moodle_standard_password',
        ),
    ]
