# Generated by Django 3.1.5 on 2021-05-06 13:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0059_auto_20210506_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Anmeldung'),
        ),
    ]
