# Generated by Django 3.1.5 on 2021-05-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0060_auto_20210506_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_events', to='events.eventlocation', verbose_name='Veranstaltungsort'),
        ),
    ]
