# Generated by Django 3.1.5 on 2021-05-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0061_auto_20210506_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='frontend_flag',
            field=models.BooleanField(default=True, verbose_name='im Frontend zeigen?'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_recipient',
            field=models.EmailField(blank=True, help_text='an diese Adresse werden Anmeldungen geschickt', max_length=254, null=True, verbose_name='Anmelde-Email an'),
        ),
    ]
