# Generated by Django 3.1.5 on 2021-05-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0063_auto_20210508_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pub_status',
            field=models.CharField(choices=[('PUB', 'öffentlich'), ('UNPUB', 'draft'), ('ARCH', 'archiviert')], default='PUB', help_text='veröffentlicht: sichtbar und buchbar; draft: nicht sichtbar, nicht buchbar; archiviert: nicht sichtbar, nicht buchbar', max_length=8, verbose_name='Status Veröffentlichung'),
        ),
    ]
