# Generated by Django 3.1.5 on 2021-07-05 06:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0067_auto_20210610_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_possible',
            field=models.BooleanField(default=True, verbose_name='Anmeldung möglich'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2021, 7, 5), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
