# Generated by Django 3.1.5 on 2021-07-08 06:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0068_auto_20210705_0611"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmember",
            name="member_type",
            field=models.CharField(
                null=True,
                blank=True,
                default=None,
                max_length=1,
                verbose_name="Art der Mitgliedschaft",
            ),
        ),
        migrations.AddField(
            model_name="eventmember",
            name="takes_part",
            field=models.BooleanField(default=True, verbose_name="Teilnahme"),
        ),
        migrations.AddField(
            model_name="eventmember",
            name="vote_transfer",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Stimmübertragung"
            ),
        ),
        migrations.AddField(
            model_name="eventmember",
            name="vote_transfer_check",
            field=models.BooleanField(
                default=True, verbose_name="Check Stimmübertragung"
            ),
        ),
        migrations.AlterField(
            model_name="eventhighlight",
            name="event",
            field=models.ForeignKey(
                limit_choices_to={
                    "first_day__gte": datetime.date(2021, 7, 8),
                    "pub_status": "PUB",
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlight",
                to="events.event",
            ),
        ),
    ]
