# Generated by Django 3.1.5 on 2021-07-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0069_auto_20210708_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_form',
            field=models.CharField(choices=[('s', 'Standard'), ('m', 'MV/ZW')], default='s', max_length=1, verbose_name='Anmeldeformular'),
        ),
    ]
