# Generated by Django 3.1.5 on 2021-07-26 22:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0072_auto_20210720_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='mv_check',
            field=models.CharField(default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='zw_check',
            field=models.CharField(default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2021, 7, 26), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
