# Generated by Django 3.1.5 on 2021-08-22 10:53

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0079_auto_20210822_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlocation',
            name='country',
            field=django_countries.fields.CountryField(default='DE', max_length=3, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='country',
            field=django_countries.fields.CountryField(default='DE', max_length=3, verbose_name='Land'),
        ),
    ]
