# Generated by Django 3.1.5 on 2021-08-27 10:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0080_auto_20210822_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='regio_group',
            field=models.CharField(blank=True, choices=[('BAY', 'Bayern'), ('BER', 'Berlin'), ('FFM', 'Frankfurt'), ('FR', 'Freiburg'), ('HH', 'Hamburg'), ('KBO', 'Köln/Bonn'), ('L', 'Leipzig'), ('NDS', 'Niedersachsen'), ('RHR', 'Rhein/Ruhr'), ('S', 'Stuttgart'), ('HB', 'Bremen'), ('RHN', 'Rhein/Neckar'), ('NFU', 'Nürnberg/Fürth'), ('OWL', 'Ostwestfalen-Lippe'), ('THU', 'Thüringen')], default=None, max_length=3, null=True, verbose_name='Regionalgruppe'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2021, 8, 27), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='country',
            field=django_countries.fields.CountryField(default='DE', max_length=2, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='country',
            field=django_countries.fields.CountryField(default='DE', max_length=2, verbose_name='Land'),
        ),
    ]
