# Generated by Django 3.1.5 on 2021-08-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0081_auto_20210827_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='regio_group',
            field=models.CharField(blank=True, choices=[('KA', '---'), ('BAY', 'Bayern'), ('BER', 'Berlin'), ('FFM', 'Frankfurt'), ('FR', 'Freiburg'), ('HH', 'Hamburg'), ('KBO', 'Köln/Bonn'), ('L', 'Leipzig'), ('NDS', 'Niedersachsen'), ('RHR', 'Rhein/Ruhr'), ('S', 'Stuttgart'), ('HB', 'Bremen'), ('RHN', 'Rhein/Neckar'), ('NFU', 'Nürnberg/Fürth'), ('OWL', 'Ostwestfalen-Lippe'), ('THU', 'Thüringen')], default='KA', max_length=3, null=True, verbose_name='Regionalgruppe'),
        ),
    ]
