# Generated by Django 3.1.5 on 2021-09-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0085_auto_20210912_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsponsor',
            name='position',
        ),
        migrations.AddField(
            model_name='eventsponsorthrough',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
