# Generated by Django 3.1.5 on 2021-12-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0090_auto_20211202_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdocument',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='eventdocument',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titel'),
        ),
    ]
