# Generated by Django 3.1.5 on 2021-12-13 19:26

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0091_auto_20211202_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOrganizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='angelegt am')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, verbose_name='Veranstaltunger Website')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='contribution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VFLL-Beteiligung'),
        ),
        migrations.AddField(
            model_name='event',
            name='notes_internal',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='interne Hinweise'),
        ),
        migrations.AlterField(
            model_name='eventdocument',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_documents', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventdocument',
            name='upload',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2021, 12, 13), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizer_events', to='events.eventorganizer', verbose_name='Veranstalter'),
        ),
    ]
