# Generated by Django 3.1.5 on 2021-12-14 07:05

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0092_auto_20211213_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Teaser'),
        ),
        migrations.AlterField(
            model_name='event',
            name='objectives',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Lernziele'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prerequisites',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Voraussetzungen'),
        ),
        migrations.AlterField(
            model_name='event',
            name='target_group',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zielgruppe'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2021, 12, 14), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventorganizer',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kontakt'),
        ),
        migrations.AlterField(
            model_name='eventorganizer',
            name='url',
            field=models.URLField(blank=True, verbose_name='Veranstalter Website'),
        ),
    ]
