# Generated by Django 3.1.5 on 2022-02-02 09:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0093_auto_20211214_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2022, 2, 2), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='address_line',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresszusatz'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='address_line',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresszusatz'),
        ),
        migrations.AlterField(
            model_name='eventmember',
            name='check',
            field=models.BooleanField(default=False, verbose_name='Einverständnis'),
        ),
    ]
