# Generated by Django 3.1.5 on 2022-02-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0094_auto_20220202_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Firma'),
        ),
    ]
