# Generated by Django 3.1.5 on 2022-02-09 08:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0096_auto_20220203_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventurl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2022, 2, 9), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
