# Generated by Django 3.1.5 on 2022-02-16 11:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0097_auto_20220209_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='academic',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2022, 2, 16), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
