# Generated by Django 3.1.5 on 2022-02-23 06:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0098_auto_20220216_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='video_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2022, 2, 23), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
