# Generated by Django 3.1.5 on 2022-02-23 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0099_auto_20220223_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizer_events', to='events.eventorganizer', verbose_name='Veranstalter'),
        ),
    ]
