# Generated by Django 3.1.5 on 2022-03-03 23:50

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0100_auto_20220223_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='methods',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Methoden'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2022, 3, 3), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
