# Generated by Django 3.1.5 on 2022-06-10 11:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0102_auto_20220525_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_form',
            field=models.CharField(choices=[('s', 'Standard'), ('m', 'MV/ZW'), ('f', 'Fachtagung 2022/MV')], default='s', max_length=1, verbose_name='Anmeldeformular'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2022, 6, 10), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
