# Generated by Django 3.1.5 on 2022-06-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0104_auto_20220624_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
