# Generated by Django 3.1.5 on 2023-06-20 07:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0111_auto_20220918_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventmember'),
        ),
        migrations.AlterField(
            model_name='event',
            name='moodle_new_user_flag',
            field=models.BooleanField(default=False, help_text='Hier kann für den Kurs festgelegt werden, ob neue Moodle-User die automatische Begrüßungsmail von Moodle (mit Zufallspasswort) bekommen (default=False). Ist das Feld nicht angeklickt, verschickt Moodle keine E-Mail und die neuen User können sich mit dem Standardpasswort anmelden. Bein Änderung dieses Feldes immer erst abspeichern!', verbose_name='Autom. E-Mail an neue Moodle-User'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2023, 6, 20), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
