# Generated by Django 3.1.5 on 2023-06-20 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0112_auto_20230620_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmember',
            name='parent',
        ),
        migrations.AddField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event'),
        ),
    ]
