# Generated by Django 3.1.5 on 2023-06-20 07:31

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0113_auto_20230620_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='angelegt am')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('frontend_flag', models.BooleanField(default=True, verbose_name='im Frontend zeigen?')),
                ('label', models.CharField(help_text='eindeutiger Kurzname', max_length=64, unique=True, verbose_name='Kurzname')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Teaser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventcollection'),
        ),
    ]
