# Generated by Django 3.1.5 on 2023-06-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0114_auto_20230620_0731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='parent',
            new_name='event_collection',
        ),
    ]
