# Generated by Django 3.1.5 on 2023-06-20 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0115_auto_20230620_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcollection'),
        ),
    ]
