# Generated by Django 3.1.5 on 2023-06-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0116_auto_20230620_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
