# Generated by Django 3.1.5 on 2023-06-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0117_event_last_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcollection',
            name='first_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
