# Generated by Django 3.1.5 on 2023-06-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0118_eventcollection_first_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcollection',
            name='last_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
