# Generated by Django 3.1.5 on 2023-07-04 21:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0124_auto_20230628_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Hier kommt der reduzierte Mitgliederpreis rein. Der volle Preis ist 35% höher, wobei auf 10 Euro aufgerundet wird.', max_digits=10, verbose_name='Mitgliederpreis'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2023, 7, 4), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
