# Generated by Django 3.1.5 on 2023-07-12 12:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0126_auto_20230711_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayLessAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_premium', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='normaler Preis')),
                ('price_members', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis für Mitglieder')),
            ],
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2023, 7, 12), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='payless_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.paylessaction'),
        ),
    ]
