# Generated by Django 3.1.5 on 2023-07-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0127_auto_20230712_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paylessaction',
            options={'verbose_name': 'Pay-Less-Aktion', 'verbose_name_plural': 'Pay-Less-Aktionen'},
        ),
        migrations.AddField(
            model_name='event',
            name='oneliner',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
