# Generated by Django 3.1.5 on 2023-07-21 14:23

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0128_auto_20230712_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='paylessaction',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Anzeigetitel'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2023, 7, 21), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
        migrations.AlterField(
            model_name='paylessaction',
            name='price_members',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rabattpreis'),
        ),
    ]
