# Generated by Django 3.1.5 on 2023-07-24 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0129_auto_20230721_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vfll_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2023, 7, 24), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
