# Generated by Django 3.1.5 on 2023-07-28 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0130_auto_20230724_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='paylessaction',
            name='percents',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='paylessaction',
            name='type',
            field=models.CharField(choices=[('n', 'n für m'), ('p', 'Prozente')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2023, 7, 28), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
