# Generated by Django 3.1.5 on 2023-08-03 05:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0133_auto_20230801_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='registration',
            field=models.BooleanField(default=True, verbose_name='Anmeldung möglich'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2023, 8, 3), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
