# Generated by Django 3.1.5 on 2023-08-09 13:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0134_auto_20230803_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2023, 8, 9), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
        migrations.AlterField(
            model_name='paylessaction',
            name='price_members',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Rabattpreis'),
        ),
        migrations.AlterField(
            model_name='paylessaction',
            name='price_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='normaler Preis'),
        ),
    ]
