# Generated by Django 3.1.5 on 2023-08-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0135_auto_20230809_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylessaction',
            name='price_members',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rabattpreis'),
        ),
        migrations.AlterField(
            model_name='paylessaction',
            name='price_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='normaler Preis'),
        ),
    ]
