# Generated by Django 3.1.5 on 2023-08-11 12:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0136_auto_20230809_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventformat',
            name='moodle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2023, 8, 11), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
