# Generated by Django 3.1.5 on 2023-08-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0138_auto_20230818_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylessaction',
            name='percents',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Prozente'),
        ),
    ]
