# Generated by Django 3.1.5 on 2023-09-07 17:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0139_auto_20230818_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcollection',
            options={'ordering': ('first_day',), 'verbose_name': 'Bildungsangebot', 'verbose_name_plural': 'Bildungsangebote'},
        ),
        migrations.AddField(
            model_name='event',
            name='registration_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='direct_payment',
            field=models.BooleanField(default=False, verbose_name='Warenkorb'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2023, 9, 7), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
