# Generated by Django 3.1.5 on 2023-12-11 12:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0140_auto_20230907_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='open_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Anmeldefrist Beginn'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2023, 12, 11), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
