# Generated by Django 3.1.5 on 2023-12-19 13:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0141_auto_20231211_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('file', private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='', verbose_name='File')),
            ],
        ),
        migrations.AlterModelOptions(
            name='eventdocument',
            options={'verbose_name': 'öffentliches Dokument', 'verbose_name_plural': 'öffentliche Dokumente'},
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2023, 12, 19), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
        migrations.CreateModel(
            name='PrivatDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='angelegt am')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('upload', private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='uploaded_private_documents/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_private_documents', to='events.event')),
            ],
            options={
                'verbose_name': 'private Dokument',
                'verbose_name_plural': 'private Dokumente',
            },
        ),
    ]
