# Generated by Django 3.1.5 on 2023-12-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0142_auto_20231219_1324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivatDocument',
            new_name='PrivateDocument',
        ),
    ]
