# Generated by Django 3.2.15 on 2023-12-28 16:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0143_auto_20231219_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatedocument',
            options={'verbose_name': 'privates Dokument', 'verbose_name_plural': 'private Dokumente'},
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2023, 12, 28), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
