# Generated by Django 3.2.15 on 2024-02-02 16:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0150_alter_eventhighlight_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2024, 2, 2), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
        migrations.CreateModel(
            name='EventMemberChangeDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='angelegt am')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('action', models.CharField(blank=True, max_length=40, null=True)),
                ('change_date', models.DateTimeField()),
                ('event_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_dates', to='events.eventmember')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
