# Generated by Django 3.2.15 on 2024-03-19 10:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0156_alter_eventhighlight_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdocument',
            name='emphasize',
            field=models.BooleanField(default=False, verbose_name='hervorheben'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2024, 3, 19), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
