# Generated by Django 3.2.15 on 2024-05-06 21:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0157_auto_20240319_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='edit_in_frontend',
            field=models.BooleanField(default=False, verbose_name='editierbar im Frontend?'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2024, 5, 6), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
