# Generated by Django 3.2.15 on 2024-06-23 20:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0159_auto_20240515_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_date',
            field=models.BooleanField(default=True, verbose_name='Datum anzeigen'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2024, 6, 23), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
