# Generated by Django 3.2.15 on 2024-07-05 11:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0160_auto_20240623_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_form',
            field=models.CharField(choices=[('s', 'Standard'), ('m', 'MV/ZW'), ('f', 'Fachtagung 2022/MV'), ('f24', 'Fachtagung 2024/MV')], default='s', max_length=3, verbose_name='Anmeldeformular'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2024, 7, 5), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
