# Generated by Django 3.2.15 on 2024-07-10 11:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0161_auto_20240705_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventday',
            name='end_time_remark',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Ergänzung Endzeit'),
        ),
        migrations.AddField(
            model_name='eventday',
            name='start_time_remark',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Ergänzung Startzeit'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2024, 7, 10), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
