# Generated by Django 3.2.15 on 2024-08-08 14:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('events', '0162_auto_20240710_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visible_to_groups',
            field=models.ManyToManyField(blank=True, related_name='visible_events', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2024, 8, 8), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
