# Generated by Django 3.2.15 on 2025-01-10 20:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0164_auto_20240901_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='belongs_to_all_events',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eventhighlight',
            name='event',
            field=models.ForeignKey(limit_choices_to={'first_day__gte': datetime.date(2025, 1, 10), 'pub_status': 'PUB'}, on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='events.event'),
        ),
    ]
