# Generated by Django 3.2.15 on 2025-04-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0167_auto_20250408_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.ImageField(default='images/vfll_logo_rot_Bild.jpg', upload_to='home/'),
        ),
    ]
