# Generated by Django 3.2.15 on 2025-04-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0169_auto_20250409_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='keywords',
            field=models.CharField(blank=True, help_text='Keywords für SEO, bitte mit Komma getrennt angeben.', max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='event',
            name='keywords',
            field=models.CharField(blank=True, help_text='Keywords für SEO, bitte mit Komma getrennt angeben.', max_length=255),
        ),
    ]
