# Generated by Django 4.2.20 on 2025-03-16 08:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0170_alter_eventhighlight_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventmember",
            old_name="check",
            new_name="agree",
        ),
        migrations.AlterField(
            model_name="eventhighlight",
            name="event",
            field=models.ForeignKey(
                limit_choices_to={
                    "first_day__gte": datetime.date(2025, 3, 16),
                    "pub_status": "PUB",
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlight",
                to="events.event",
            ),
        ),
    ]
