# Generated by Django 4.2.20 on 2025-05-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0170_auto_20250409_2301"),
        ("events", "0174_alter_eventhighlight_event"),
    ]

    operations = []
