# Generated by Django 4.2.20 on 2025-05-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0171_auto_20250413_1523"),
        ("events", "0175_merge_20250518_1923"),
    ]

    operations = []
