# Generated by Django 4.2.20 on 2025-06-20 09:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0176_merge_20250525_1058"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventimage",
            name="image_form",
            field=models.CharField(
                choices=[("r", "rechteckig"), ("s", "quadratisch"), ("c", "rund")],
                default="r",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="eventhighlight",
            name="event",
            field=models.ForeignKey(
                limit_choices_to={
                    "first_day__gte": datetime.date(2025, 6, 20),
                    "pub_status": "PUB",
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlight",
                to="events.event",
            ),
        ),
    ]
