# Generated by Django 3.2.15 on 2026-04-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='registration',
        ),
    ]
