# Generated by Django 3.2.15 on 2025-02-23 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0021_auto_20250222_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_number', models.CharField(max_length=255)),
                ('invoice_date', models.DateTimeField(blank=True, null=True, verbose_name='Rechnungsdatum')),
                ('invoice_type', models.CharField(choices=[('s', 'Storno'), ('i', 'Rechnung')], default='i', max_length=1)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
            },
        ),
        migrations.CreateModel(
            name='StornoInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storno_invoice', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Storno Rechnung',
                'verbose_name_plural': 'Storno Rechnungen',
            },
        ),
    ]
