# Generated by Django 3.2.15 on 2025-02-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='mail_sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rechnungsversand'),
        ),
    ]
