# Generated by Django 3.2.15 on 2025-02-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_receipt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rechnungseingang'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='replacement_date',
            field=models.CharField(blank=True, help_text='Zum Überschreiben des automatisch erzeugten Veranstaltungsdatums. Funktioniert nur, wenn die Rechnung nur 1 NICHT STORNIERTE Veranstaltung enthält.', max_length=40, null=True, verbose_name='Ersatzangabe Event Datum'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='replacement_event',
            field=models.CharField(blank=True, help_text='Zum Überschreiben des automatisch erzeugten Veranstaltungstitels. Funktioniert nur, wenn die Rechnung nur 1 NICHT STORNIERTE Veranstaltung enthält.', max_length=255, null=True, verbose_name='Ersatzangabe Event Name'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='use_replacements',
            field=models.BooleanField(default=False, help_text='Anklicken, um Ersatzangaben zu benutzen', verbose_name='Ersatzangaben benutzen'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=255, verbose_name='Rechnungsnummer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('s', 'Storno'), ('i', 'Rechnung')], default='i', max_length=1, verbose_name='Rechnungsart'),
        ),
    ]
