# Generated by Django 3.2.15 on 2025-02-28 16:27

from django.db import migrations, models
import django.utils.timezone
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='stornoinvoice',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Betrag'),
        ),
        migrations.AddField(
            model_name='stornoinvoice',
            name='invoice_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Rechnungsdatum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stornoinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rechnungsnummer'),
        ),
        migrations.AddField(
            model_name='stornoinvoice',
            name='invoice_receipt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rechnungseingang'),
        ),
        migrations.AddField(
            model_name='stornoinvoice',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='bezahlt'),
        ),
        migrations.AddField(
            model_name='stornoinvoice',
            name='pdf',
            field=private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='stornos/'),
        ),
    ]
