# Generated by Django 4.2.20 on 2025-03-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0006_auto_20250228_1627"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stornoinvoice",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Der Betrag erscheint auf der Storno-Rechnung mit Minuszeichen.",
                max_digits=10,
                null=True,
                verbose_name="Betrag",
            ),
        ),
    ]
