# Generated by Django 4.2.20 on 2025-06-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0007_alter_stornoinvoice_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["-invoice_date"],
                "verbose_name": "Rechnung",
                "verbose_name_plural": "Rechnungen",
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_export",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Exportdatum"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="pdf_export",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Pdf-Export"
            ),
        ),
    ]
