# Generated by Django 4.2.20 on 2025-06-10 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0008_alter_invoice_options_invoice_invoice_export_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardInvoice",
            fields=[],
            options={
                "verbose_name": "Rechnung",
                "verbose_name_plural": "Rechnungen",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("invoices.invoice",),
        ),
        migrations.AddField(
            model_name="invoice",
            name="storno_invoice",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"invoice_type": "s"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="original_invoice",
                to="invoices.invoice",
            ),
        ),
        migrations.DeleteModel(
            name="StornoInvoice",
        ),
        migrations.CreateModel(
            name="StornoInvoice",
            fields=[],
            options={
                "verbose_name": "Storno-Rechnung",
                "verbose_name_plural": "Storno-Rechnungen",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("invoices.invoice",),
        ),
    ]
