
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBB
    
    XXXXXXXX
        XXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
                XXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                XXX XXXX XXXX X X XXXXXXXXXXXXXXXXXXXXXX XXXX X
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X
                        XXXXXXXXXXXXXXXXXXX XX XXXXXXXX X X XXXXXXXXXXXXXX X XXXXX X
                            XXXXXXXXXXXXXXXXXXX
                        X
                    XXX
                X
            XXX
        XXXXX
    XXXXXXXXX
BBBBBBBB