# Generated by Django 4.0.5 on 2026-05-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfllnl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('image', models.ImageField(upload_to='newsletter_images/', verbose_name='Bild')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
            ],
            options={
                'verbose_name': 'Newsletter-Bild',
                'verbose_name_plural': 'Newsletter-Bilder',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
