# Generated by Django 4.2.20 on 2025-07-01 11:02

import bugz.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="angelegt am"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, verbose_name="geändert am"),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(max_length=2000, verbose_name="Beschreibung"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="angelegt am"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, verbose_name="geändert am"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titel")),
                (
                    "description",
                    models.TextField(max_length=2000, verbose_name="Beschreibung"),
                ),
                (
                    "task_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Bug"), (2, "Feature")],
                        default=1,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "niedrig"), (2, "mittel"), (3, "hoch")],
                        default=1,
                        verbose_name="Priorität",
                    ),
                ),
                (
                    "close_date",
                    models.DateField(
                        blank=True,
                        default=bugz.models.return_date_time,
                        null=True,
                        verbose_name="erledigen bis",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "offen"), (2, "in Arbeit"), (3, "fertig")],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bugz.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="angelegt am"),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, verbose_name="geändert am"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titel")),
                (
                    "description",
                    models.TextField(max_length=2000, verbose_name="Beschreibung"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bugz.task",
                        verbose_name="Kommentar",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
