# Generated by Django 3.1.5 on 2021-02-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugz', '0002_auto_20210222_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='close_date',
            field=models.DateField(blank=True, null=True, verbose_name='erledigen bis'),
        ),
    ]
