# Generated by Django 3.1.5 on 2021-02-22 20:26

import bugz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugz', '0005_auto_20210222_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='close_date',
            field=models.DateField(blank=True, default=bugz.models.return_date_time, null=True, verbose_name='erledigen bis'),
        ),
    ]
