# Generated by Django 3.1.5 on 2021-02-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugz', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='created_by',
        ),
    ]
