"""
Django settings for eventmanager project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_PATH = os.path.realpath(os.path.dirname(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

INTERNAL_IPS = [
    "127.0.0.1",
]

# Default Auto Field
DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# site id
SITE_ID = 1


# Application definition

INSTALLED_APPS = [
    #'jet.dashboard',
    #'jet',
    # "grappelli.dashboard",
    #"grappelli",
    'admin_confirm',
    "admin_interface",
    "colorfield",
    "django_admin_index",
    "ordered_model",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "django_filters",
    "django_tables2",
    "django_countries",
    "rest_framework",
    # 2FA
    "django_otp",
    "django_otp.plugins.otp_totp",
    # 'two_factor',
    # 'two_factor.plugins.phonenumber',
    # third party
    "mjml",
    "mailqueue",
    "fontawesomefree",
    "crispy_forms",
    "crispy_tailwind",
    "ckeditor",
    "ckeditor_uploader",
    "easy_thumbnails",
    "tailwind",
    "inline_actions",
    "fieldsets_with_inlines",
    "wkhtmltopdf",
    "bootstrap_modal_forms",
    "widget_tweaks",
    "tinymce",
    "embed_video",
    "hitcount",
    "paypal.standard.ipn",  # django-paypal
    "ajax_datatable",
    "django_crontab",
    "markdownify.apps.MarkdownifyConfig",
    "admin_export_action",
    "honeypot",
    # "newsletter",
    "meta",
    # tailwind theme app
    "fobi_theme",
    "django_browser_reload",
    # lokale apps
    "events.apps.EventsConfig",
    "users.apps.UsersConfig",
    "moodle.apps.MoodleConfig",
    "bugz.apps.BugzConfig",
    "shop.apps.ShopConfig",
    "payment.apps.PaymentConfig",
    "faqs.apps.FaqsConfig",
    "reports.apps.ReportsConfig",
    # "simple_newsletter",
    "vfllnl",
    "mailings.apps.MailingsConfig",
    "invoices.apps.InvoicesConfig",
    "utilities.apps.UtilitiesConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_otp.middleware.OTPMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "events.middleware.MaintenanceModeMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    "honeypot.middleware.HoneypotMiddleware",
    "django.middleware.locale.LocaleMiddleware",
]

ROOT_URLCONF = "eventmanager.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "events.custom_context_processor.category_renderer",
                "events.custom_context_processor.event_in_frontend_context",
                "events.custom_context_processor.events_in_frontend_context",
                "events.custom_context_processor.show_newsletter_signup",
                "events.custom_context_processor.dev_ribbon",
                "shop.context_processors.cart",
            ],
        },
    },
]

WSGI_APPLICATION = "eventmanager.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTHENTICATION_BACKENDS = ("users.backend.EmailOrUsernameBackend",)


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "de"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# login
# LOGIN_URL = "login"
LOGIN_URL = "users:login"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

STATICFILES_DIRS = [
    os.path.join(PROJECT_PATH, "static"),
]

# Media files (Images)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Crsipy forms

CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"

CRISPY_TEMPLATE_PACK = "tailwind"
# CRISPY_TEMPLATE_PACK = "bootstrap4"

# Ckeditor config
CKEDITOR_JQUERY_URL = "https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"

CKEDITOR_UPLOAD_PATH = "event-details/"
CKEDITOR_CONFIGS = {
    "default": {
        "versionCheck": False,
        "toolbar": None,
    },
    "short": {
        "versionCheck": False,
        "toolbar": "Short",
        "height": 100,
        "toolbar_Short": [
            [
                "Bold",
                "Italic",
                "Link",
                "Unlink",
                "NumberedList",
                "BulletedList",
            ],
            ["FontSize"],
            ["TextColor", "BGColor"],
        ],
    },
}


# easy thumbnails
THUMBNAIL_ALIASES = {
    "": {
        "logo": {"size": (130, 130), "crop": True},
    },
}

# Tailwind css
TAILWIND_APP_NAME = "fobi_theme"

# for JET WORKING PROPERLY
X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

# GRAPPELLI setting

GRAPPELLI_ADMIN_TITLE = "FOBI Eventmanager"
GRAPPELLI_INDEX_DASHBOARD = "eventmanager.dashboard.CustomIndexDashboard"

# REST FRAMEWORK
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly"
    ]
}

# SESSION, SHOP
CART_SESSION_ID = "cart"

# django-paypal settings
PAYPAL_BUY_BUTTON_IMAGE = (
    "https://veranstaltungskalender.vfll.de/static/images/checkout-logo-small-de.png"
)

# Tooltips

TOOLTIPS = {"waiting": "Rechnungsstellung, wenn Teilnahme bestätigt"}

# faq settings
FAQ_SETTINGS = []

# action settings
ONLY_NOT_FULL_EVENTS_CAN_HAVE_ACTION = True

# copy settings
COPY_ONLY_ALLOWED_FOR_SINGLE_OBJECT = True

# payment and registration texts
PAY_NOW_TEXT = "Jetzt kaufen"
REGISTER_NOW_TEXT = "Jetzt kostenpflichtig anmelden"
REGISTER_NOW_FREE_TEXT = "Jetzt anmelden"
REGISTER_NOW_TEXT_WAITING = "Jetzt anmelden"

# disable sitewide django-admin-export-action
ADMIN_EXPORT_ACTION = {"ENABLE_SITEWIDE": False}

# honeypot
HONEYPOT_FIELD_NAME = "secret_key"

# invoiceninja settings
INVOICE_NINJA_API_KEY = os.environ.get("INVOICE_NINJA_API_KEY", None)
INVOICE_NINJA_BASE_URL = os.environ.get("INVOICE_NINJA_BASE_URL", None)

# django-newsletter settings
# Using easy-thumbnails
NEWSLETTER_THUMBNAIL = "easy-thumbnails"
# Using django-tinymce
NEWSLETTER_RICHTEXT_WIDGET = "tinymce.widgets.TinyMCE"
