# Generated by Django 3.1.5 on 2023-06-21 19:50

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0121_event_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='angelegt am')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('address_line', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresszusatz')),
                ('street', models.CharField(blank=True, max_length=55, null=True, verbose_name='Straße')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stadt')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bundesland')),
                ('postcode', models.CharField(blank=True, max_length=64, null=True, verbose_name='PLZ')),
                ('country', django_countries.fields.CountryField(default='DE', max_length=2, verbose_name='Land')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='events.event')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-date_created'], name='shop_order_date_cr_c0e4ae_idx'),
        ),
    ]
