# Generated by Django 3.1.5 on 2023-06-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20230621_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='academic',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Titel'),
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Firma'),
        ),
    ]
