# Generated by Django 3.1.5 on 2023-06-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20230623_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounted',
            field=models.BooleanField(default=False, verbose_name='reduziert'),
        ),
    ]
