# Generated by Django 3.1.5 on 2023-07-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_discounted'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='premium_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='discounted',
            field=models.BooleanField(default=True, verbose_name='reduziert'),
        ),
    ]
