# Generated by Django 3.1.5 on 2023-08-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20230704_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_action_price',
            field=models.BooleanField(default=False),
        ),
    ]
