# Generated by Django 3.1.5 on 2023-08-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderitem_is_action_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('n', '---'), ('p', 'PayPal'), ('r', 'Rechnung')], default='n', max_length=1, verbose_name='Bezahltyp'),
        ),
    ]
