# Generated by Django 3.2.15 on 2024-01-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20230818_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='download_marker',
            field=models.BooleanField(default=False),
        ),
    ]
