# Generated by Django 3.2.15 on 2024-01-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_download_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mail_sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rechnungsversand'),
        ),
    ]
