# Generated by Django 3.2.15 on 2024-02-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reminder_sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Mahnungsversand'),
        ),
    ]
