# Generated by Django 3.2.15 on 2024-02-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_reminder_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='storno',
            field=models.BooleanField(default=False, verbose_name='Storno'),
        ),
    ]
