# Generated by Django 3.2.15 on 2024-10-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20240901_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('n', '---'), ('p', 'PayPal'), ('r', 'Rechnung')], default='r', max_length=1, verbose_name='Bezahltyp'),
        ),
    ]
