# Generated by Django 3.2.15 on 2024-10-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_receipt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zahlungseingang'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rechnungsdatum'),
        ),
    ]
