# Generated by Django 3.2.15 on 2025-02-13 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_ordernote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordernote',
            options={'ordering': ['-date_created'], 'verbose_name': 'Notiz', 'verbose_name_plural': 'Notizen'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='note',
            field=models.TextField(verbose_name='Notiz'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='shop.order', verbose_name='Bestellung'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titel'),
        ),
    ]
