# Generated by Django 3.2.15 on 2025-04-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20250213_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('r', 'registriert'), ('w', 'Warteliste'), ('s', 'storniert'), ('n', 'nicht erschienen'), ('u', 'unklar'), ('c', 'Veranstaltung abgesagt')], default='r', max_length=1),
        ),
    ]
