# Generated by Django 4.2.20 on 2025-05-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0021_alter_orderitem_status"),
        ("shop", "0021_auto_20250222_0738"),
    ]

    operations = []
