# Generated by Django 4.2.20 on 2025-03-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invoices", "0007_alter_stornoinvoice_amount"),
        ("mailqueue", "0009_alter_attachment_file_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceMessage",
            fields=[
                (
                    "mailermessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mailqueue.mailermessage",
                    ),
                ),
                (
                    "mail_type",
                    models.CharField(
                        choices=[("s", "Storno"), ("i", "Rechnung")],
                        default="i",
                        max_length=1,
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rechnung Mail",
                "verbose_name_plural": "Rechnung Mails",
            },
            bases=("mailqueue.mailermessage",),
        ),
    ]
