# Generated by Django 3.2.15 on 2026-04-22 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailqueue', '0009_alter_attachment_file_attachment'),
        ('events', '0019_auto_20260422_2006'),
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationMessage',
            fields=[
                ('mailermessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mailqueue.mailermessage')),
                ('confirmation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message', to='events.confirmation')),
            ],
            options={
                'verbose_name': 'Teilnahmebestätigungs-Mail',
                'verbose_name_plural': 'Teilnahmebestätigungs-Mails',
            },
            bases=('mailqueue.mailermessage',),
        ),
    ]
