# Generated by Django 3.2.15 on 2025-02-23 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicemessage',
            name='order',
        ),
        migrations.AddField(
            model_name='invoicemessage',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoice'),
        ),
    ]
