# Generated by Django 3.2.15 on 2025-02-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_auto_20250223_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicemessage',
            options={'verbose_name': 'Rechnung Mail', 'verbose_name_plural': 'Rechnung Mails'},
        ),
    ]
