# Generated by Django 3.2.15 on 2025-02-28 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20250228_1627'),
        ('mailings', '0003_alter_invoicemessage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemessage',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message', to='invoices.invoice'),
        ),
    ]
