# Generated by Django 4.0.5 on 2026-05-02 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_newsletterimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterImage',
        ),
    ]
