# Generated by Django 3.2.15 on 2024-02-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.PositiveSmallIntegerField(help_text='Reihenfolge der Programme in der Anezige', null=True, verbose_name='Reihenfolge'),
        ),
    ]
