# Generated by Django 3.2.15 on 2025-04-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='use_mjml',
            field=models.BooleanField(default=False),
        ),
    ]
