# Generated by Django 3.2.15 on 2025-04-16 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simple_newsletter', '0002_auto_20250416_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='header',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='message',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
