# Generated by Django 3.2.15 on 2025-04-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_newsletter', '0003_auto_20250416_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'active'), ('c', 'cancelled')], default='a', max_length=1, null=True),
        ),
    ]
