# Generated by Django 4.2.20 on 2025-06-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_newsletter", "0004_emailtemplate_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newslettersubscription",
            options={
                "verbose_name": "Newsletter Subscription",
                "verbose_name_plural": "Newsletter Subscriptions",
            },
        ),
        migrations.RemoveField(
            model_name="newslettersubscription",
            name="id",
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="status",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="newslettersubscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
