# Generated by Django 4.2.20 on 2025-06-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_newsletter", "0005_alter_newslettersubscription_options_and_more"),
    ]

    operations = [
        
    ]
