# Generated by Django 3.1.5 on 2021-03-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodleuser',
            options={'ordering': ('lastname',)},
        ),
    ]
